apiVersion: v1
kind: Service
metadata:
  name: %{SERVICE_NAME}
spec:
  type: ClusterIP
  selector:
    app: %{SERVICE_NAME}
  ports:
    - name: http
      port: %{PORT}
      protocol: TCP
      targetPort: http
    - port: 9999
      targetPort: grpc
      protocol: TCP
      name: grpc
